"""Add papers table

Revision ID: 8fddc08f2d68
Revises: 
Create Date: 2025-05-29 08:20:02.662980

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '8fddc08f2d68'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('papers',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('arxiv_id', sa.String(length=20), nullable=False),
    sa.Column('title', sa.Text(), nullable=False),
    sa.Column('authors', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('abstract', sa.Text(), nullable=False),
    sa.Column('pdf_url', sa.Text(), nullable=False),
    sa.Column('categories', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('submission_date', sa.Date(), nullable=False),
    sa.Column('relevance_score', sa.Float(), nullable=True),
    sa.Column('keyword_matches', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('processed', sa.Boolean(), nullable=True),
    sa.Column('summarized', sa.Boolean(), nullable=True),
    sa.Column('summary', sa.Text(), nullable=True),
    sa.Column('figures_extracted', sa.Boolean(), nullable=True),
    sa.Column('figure_urls', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('mentioned_in_posts', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('citation_count', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_papers_categories', 'papers', ['categories'], unique=False, postgresql_using='gin')
    op.create_index('idx_papers_processed_date', 'papers', ['processed', 'submission_date'], unique=False)
    op.create_index('idx_papers_submission_relevance', 'papers', ['submission_date', 'relevance_score'], unique=False)
    op.create_index(op.f('ix_papers_arxiv_id'), 'papers', ['arxiv_id'], unique=True)
    op.create_index(op.f('ix_papers_processed'), 'papers', ['processed'], unique=False)
    op.create_index(op.f('ix_papers_relevance_score'), 'papers', ['relevance_score'], unique=False)
    op.create_index(op.f('ix_papers_submission_date'), 'papers', ['submission_date'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_papers_submission_date'), table_name='papers')
    op.drop_index(op.f('ix_papers_relevance_score'), table_name='papers')
    op.drop_index(op.f('ix_papers_processed'), table_name='papers')
    op.drop_index(op.f('ix_papers_arxiv_id'), table_name='papers')
    op.drop_index('idx_papers_submission_relevance', table_name='papers')
    op.drop_index('idx_papers_processed_date', table_name='papers')
    op.drop_index('idx_papers_categories', table_name='papers', postgresql_using='gin')
    op.drop_table('papers')
    # ### end Alembic commands ###
